apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hello-world-alt-cert
spec:
  dnsNames:
  - helloworld-go-2.default.<DOMAIN>
  issuerRef:
    kind: ClusterIssuer
    name: ca-issuer
  secretName: helloworld-go-2
