apiVersion: serving.knative.dev/v1beta1
kind: DomainMapping
metadata:
  name: helloworld-go-dm.default.<DOMAIN>
spec:
  ref:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: helloworld-go
    namespace: default
  tls:
    secretName: helloworld-go-dm
---
apiVersion: networking.internal.knative.dev/v1alpha1
kind: ClusterDomainClaim
metadata:
  name: helloworld-go-dm.default.<DOMAIN>
spec:
  namespace: default